name: hello world
on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "A demo build"
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Test Phase
        run: echo "Running test cases"
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - name: Deploy the build
        run: echo "Deploying the app"






