name: Context variables demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to context variables
        run: |
          echo "This workflow is running on the ${{ github.event_name }} event"
          echo "The workflow was triggered by ${{ github.actor }}"
          echo "The workflow is running on the ${{ github.ref }} branch"
          echo "The workflow is running on the ${{ github.repository }} repository"  
      - name: Print all variable under github context
        run: echo "${{ toJson(github) }}"
      - name: print all variable under env context
        run: echo "${{ toJson(env) }}"
      - name: print environment variable
        run: echo "$GITHUB_SHA"
