name: Context variables demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to context variables
        run: echo "This workflow is running on the ${{ github.event_name }} event"
        run: echo "The workflow was triggered by ${{ github.actor }}"
        run: echo "The workflow is running on the ${{ github.ref }} branch"
        run: echo "The workflow is running on the ${{ github.repository }} repository"  
