name: Env Demo

on:
  workflow_dispatch:

env:
  APP_ENV: "dev"
  
jobs:
  env-demo-job:
    runs-on: ubuntu-latest
    env:
      APP_ENV: "test"
    steps:
      - name: Connecting to environment variables
        env:
          APP_ENV: "deploy"
        run: echo "App is connecting to the $APP_ENV environment"
