name: Env Demo
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: connecting to environment variables
        run: echo "App is connecting to the $APP_ENV environment"
