name: Input Demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to connect to"
        required: true
        default: "dev"
        options:
          - dev
          - test
          - deploy
      artifact_tag:
        description: "Tag to deploy"
        required: true
        default: "latest"
jobs:
  input-demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to input variables
        run: echo "App is connecting to the ${{ github.event.inputs.environment }} environment"
        run: echo "Deploying artifact with tag ${{ github.event.inputs.artifact_tag }}"
