name: Output Demo
on : push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        id: step-one
        run: echo "version=1.0.0" >> $GITHUB_OUTPUT
      - name: Step Two
        run: echo "The version is ${{ steps.step-one.outputs.version }}"
